name: MLOps Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  preprocess:
    name: Preprocess Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python src/preprocessing/preprocess.py

  train:
    name: Train Model
    runs-on: ubuntu-latest
    needs: preprocess
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python src/training/train_model.py

  evaluate:
    name: Evaluate Model
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python src/evaluate/evaluate_model.py

  deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
    needs: evaluate
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python src/deploying/deploy_model.py

  retrain:
    name: Retrain Model
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python src/retraining/retrain_model.py
